all: QRCodes

TCPEchoServer.o: TCPEchoServer.c
	gcc -c TCPEchoServer.c

TCPEchoClient.o: TCPEchoClient.c
	gcc -c TCPEchoClient.c

QRCodes: TCPEchoClient.o TCPEchoServer.o
	g++ -g -o TCPEchoClient.o TCPEchoServer.o

clean:
	rm -f QRCodes *.o